CREATE TABLE DOZENT
	( PRIVMAIL mediumtext
	, HS_MAIL mediumtext NOT NULL
	, ANSCHRIFT mediumtext
	, TELEFONNUMMER char(1)
	, NACHNAME mediumtext NOT NULL
	, PRUEFERNUMMER char(1) NOT NULL
	, TITEL mediumtext
	, VORNAME mediumtext NOT NULL
	, KUERZEL mediumtext NOT NULL )
;

CREATE TABLE FAKULTAET
	( KUERZEL mediumtext NOT NULL
	, NAME mediumtext NOT NULL
	, PRUEFERNUMMER char(1) NOT NULL )
;

CREATE TABLE HAT
	( NAME mediumtext NOT NULL
	, NAME_130 mediumtext NOT NULL )
;

CREATE TABLE IST_EINE
	( NAME mediumtext NOT NULL
	, ID char(1) NOT NULL )
;

CREATE TABLE KANN_ANBIETEN
	( PRUEFERNUMMER char(1) NOT NULL
	, NAME mediumtext NOT NULL )
;

CREATE TABLE KANN_HABEN_HAT
	( NAME mediumtext NOT NULL
	, EINSTUFUNG mediumtext NOT NULL )
;

CREATE TABLE LEHRBEAUFTRAGTE
	( ZEITFENSTER char(1) NOT NULL
	, PRUEFERNUMMER char(1) NOT NULL )
;

CREATE TABLE LEHRT
	( PRUEFERNUMMER char(1) NOT NULL
	, NAME mediumtext NOT NULL )
;

CREATE TABLE PROFESSOR
	( VORLESUNGSKONTIGENT char(1) NOT NULL
	, DWS char(1)
	, ZEITSEMESTER mediumtext NOT NULL
	, PRUEFERNUMMER char(1) NOT NULL )
;

CREATE TABLE RAUM
	( RAUMNUMMER char(1) NOT NULL
	, GEBAEUDE char(1) NOT NULL
	, STANDORT mediumtext NOT NULL
	, NAME mediumtext NOT NULL )
;

CREATE TABLE SETZT_SICH_ZUSAMMEN_AUS
	( NAME mediumtext NOT NULL
	, KUERZEL mediumtext NOT NULL )
;

CREATE TABLE STUDIENGANG
	( SPO mediumtext NOT NULL
	, ABSCHLUSS mediumtext NOT NULL
	, ZEITSEMESTER mediumtext NOT NULL
	, NAME mediumtext NOT NULL
	, KUERZEL mediumtext NOT NULL )
;

CREATE TABLE STUDIENSEMESTER
	( EINSTUFUNG mediumtext NOT NULL )
;

CREATE TABLE TAETIGKEITEN
	( DWS char(1) NOT NULL
	, ID char(1) NOT NULL
	, NAME mediumtext NOT NULL
	, ZEITSEMESTER mediumtext NOT NULL
	, PRUEFERNUMMER char(1) NOT NULL
	, PRUEFERNUMMER_118 char(1) NOT NULL
	, KUERZEL mediumtext NOT NULL )
;

CREATE TABLE VORLESUNGPLAN
	( NAME mediumtext NOT NULL
	, ZEITSEMESTER mediumtext NOT NULL
	, SWS char(1) NOT NULL
	, PRUEFERNUMMER char(1) NOT NULL )
;

CREATE TABLE VORLESUNGREAL
	( NAME mediumtext NOT NULL
	, VORLESUNGSBLOCK char(1) NOT NULL )
;

ALTER TABLE DOZENT
	ADD CONSTRAINT PK PRIMARY KEY 
	( PRUEFERNUMMER );

ALTER TABLE FAKULTAET
	ADD CONSTRAINT PK PRIMARY KEY 
	( KUERZEL mediumtext not null);

ALTER TABLE HAT
	ADD CONSTRAINT PK PRIMARY KEY 
	( NAME
	, NAME_130 );

ALTER TABLE IST_EINE
	ADD CONSTRAINT PK PRIMARY KEY 
	( NAME
	, ID );

ALTER TABLE KANN_ANBIETEN
	ADD CONSTRAINT PK PRIMARY KEY 
	( PRUEFERNUMMER
	, NAME );

ALTER TABLE KANN_HABEN_HAT
	ADD CONSTRAINT PK PRIMARY KEY 
	( NAME
	, EINSTUFUNG );

ALTER TABLE LEHRBEAUFTRAGTE
	ADD CONSTRAINT PK PRIMARY KEY 
	( PRUEFERNUMMER );

ALTER TABLE LEHRT
	ADD CONSTRAINT PK PRIMARY KEY 
	( PRUEFERNUMMER
	, NAME );

ALTER TABLE PROFESSOR
	ADD CONSTRAINT PK PRIMARY KEY 
	( PRUEFERNUMMER );

ALTER TABLE RAUM
	ADD CONSTRAINT PK PRIMARY KEY 
	( STANDORT
	, GEBAEUDE
	, RAUMNUMMER );

ALTER TABLE SETZT_SICH_ZUSAMMEN_AUS
	ADD CONSTRAINT PK PRIMARY KEY 
	( NAME
	, KUERZEL );

ALTER TABLE STUDIENGANG
	ADD CONSTRAINT PK PRIMARY KEY 
	( KUERZEL );

ALTER TABLE STUDIENSEMESTER
	ADD CONSTRAINT PK PRIMARY KEY 
	( EINSTUFUNG );

ALTER TABLE TAETIGKEITEN
	ADD CONSTRAINT PK PRIMARY KEY 
	( ID );

ALTER TABLE VORLESUNGPLAN
	ADD CONSTRAINT PK PRIMARY KEY 
	( NAME );

ALTER TABLE VORLESUNGREAL
	ADD CONSTRAINT PK PRIMARY KEY 
	( NAME );

ALTER TABLE DOZENT
	ADD CONSTRAINT DOZENT_FAKULTAET FOREIGN KEY
	( KUERZEL )
	REFERENCES FAKULTAET
	( KUERZEL ); 

ALTER TABLE FAKULTAET
	ADD CONSTRAINT FAKULTAET_DOZENT FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES DOZENT
	( PRUEFERNUMMER ); 

ALTER TABLE HAT
	ADD CONSTRAINT HAT_VORLESUNGPLAN FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGPLAN
	( NAME )
	ON DELETE CASCADE; 

ALTER TABLE HAT
	ADD CONSTRAINT HAT_VORLESUNGREAL FOREIGN KEY
	( NAME_130 )
	REFERENCES VORLESUNGREAL
	( NAME )
	ON DELETE CASCADE; 

ALTER TABLE IST_EINE
	ADD CONSTRAINT IST_EINE_VORLESUNGREAL FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGREAL
	( NAME )
	ON DELETE CASCADE; 

ALTER TABLE IST_EINE
	ADD CONSTRAINT IST_EINE_TAETIGKEITEN FOREIGN KEY
	( ID )
	REFERENCES TAETIGKEITEN
	( ID )
	ON DELETE CASCADE; 

ALTER TABLE KANN_ANBIETEN
	ADD CONSTRAINT KANN_ANBIETEN_DOZENT FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES DOZENT
	( PRUEFERNUMMER )
	ON DELETE CASCADE; 

ALTER TABLE KANN_ANBIETEN
	ADD CONSTRAINT KANN_ANBIETEN_VORLESUNGPLAN FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGPLAN
	( NAME )
	ON DELETE CASCADE; 

ALTER TABLE KANN_HABEN_HAT
	ADD CONSTRAINT KANN_HABEN_HAT_VORLESUNGPLAN FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGPLAN
	( NAME )
	ON DELETE CASCADE; 

ALTER TABLE KANN_HABEN_HAT
	ADD CONSTRAINT KANN_HABEN_HAT_STUDIENSEMESTER FOREIGN KEY
	( EINSTUFUNG )
	REFERENCES STUDIENSEMESTER
	( EINSTUFUNG )
	ON DELETE CASCADE; 

ALTER TABLE LEHRBEAUFTRAGTE
	ADD CONSTRAINT LEHRBEAUFTRAGTE_DOZENT FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES DOZENT
	( PRUEFERNUMMER )
	ON DELETE CASCADE; 

ALTER TABLE LEHRT
	ADD CONSTRAINT LEHRT_DOZENT FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES DOZENT
	( PRUEFERNUMMER )
	ON DELETE CASCADE; 

ALTER TABLE LEHRT
	ADD CONSTRAINT LEHRT_VORLESUNGREAL FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGREAL
	( NAME )
	ON DELETE CASCADE; 

ALTER TABLE PROFESSOR
	ADD CONSTRAINT PROFESSOR_DOZENT FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES DOZENT
	( PRUEFERNUMMER )
	ON DELETE CASCADE; 

ALTER TABLE RAUM
	ADD CONSTRAINT RAUM_VORLESUNGREAL FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGREAL
	( NAME ); 

ALTER TABLE SETZT_SICH_ZUSAMMEN_AUS
	ADD CONSTRAINT SETZT_SICH_ZUSAMMEN_AUS_VORLESUNGPLAN FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGPLAN
	( NAME )
	ON DELETE CASCADE; 

ALTER TABLE SETZT_SICH_ZUSAMMEN_AUS
	ADD CONSTRAINT SETZT_SICH_ZUSAMMEN_AUS_STUDIENGANG FOREIGN KEY
	( KUERZEL )
	REFERENCES STUDIENGANG
	( KUERZEL )
	ON DELETE CASCADE; 

ALTER TABLE STUDIENGANG
	ADD CONSTRAINT STUDIENGANG_FAKULTAET FOREIGN KEY
	( KUERZEL )
	REFERENCES FAKULTAET
	( KUERZEL ); 

ALTER TABLE TAETIGKEITEN
	ADD CONSTRAINT TAETIGKEITEN_DOZENT FOREIGN KEY
	( PRUEFERNUMMER_118 )
	REFERENCES DOZENT
	( PRUEFERNUMMER ); 

ALTER TABLE TAETIGKEITEN
	ADD CONSTRAINT TAETIGKEITEN_FAKULTAET FOREIGN KEY
	( KUERZEL )
	REFERENCES FAKULTAET
	( KUERZEL ); 

ALTER TABLE VORLESUNGPLAN
	ADD CONSTRAINT VORLESUNGPLAN_PROFESSOR FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES PROFESSOR
	( PRUEFERNUMMER ); 
