CREATE TABLE ANSCHRIFT
	( PRUEFERNUMMER char(1) NOT NULL
	, ORT long varchar NOT NULL
	, POSTLEITZAHL char(1) NOT NULL
	, HAUSNUMMER char(1) NOT NULL
	, STRASSE long varchar NOT NULL )
;

CREATE TABLE BESUCHT
	( NAME long varchar NOT NULL
	, EINSTUFUNG long varchar NOT NULL )
;

CREATE TABLE DOZENT
	( PRIVMAIL long varchar
	, HS_MAIL long varchar NOT NULL
	, ANSCHRIFT long varchar
	, TELEFONNUMMER char(1)
	, NACHNAME long varchar NOT NULL
	, PRUEFERNUMMER char(1) NOT NULL
	, TITEL long varchar
	, VORNAME long varchar NOT NULL
	, KUERZEL long varchar NOT NULL )
;

CREATE TABLE FAKULTAET
	( KUERZEL long varchar NOT NULL
	, NAME long varchar NOT NULL
	, PRUEFERNUMMER char(1) NOT NULL )
;

CREATE TABLE HAT
	( NAME long varchar NOT NULL
	, NAME_130 long varchar NOT NULL )
;

CREATE TABLE IST_EINE
	( NAME long varchar NOT NULL
	, ID char(1) NOT NULL )
;

CREATE TABLE KANN_ANBIETEN
	( PRUEFERNUMMER char(1) NOT NULL
	, NAME long varchar NOT NULL )
;

CREATE TABLE KANN_HABEN_HAT
	( NAME long varchar NOT NULL
	, EINSTUFUNG long varchar NOT NULL )
;

CREATE TABLE LEHRBEAUFTRAGTE
	( ZEITFENSTER char(1) NOT NULL
	, PRUEFERNUMMER char(1) NOT NULL )
;

CREATE TABLE LEHRT
	( PRUEFERNUMMER char(1) NOT NULL
	, NAME long varchar NOT NULL )
;

CREATE TABLE PROFESSOR
	( VORLESUNGSKONTIGENT char(1) NOT NULL
	, DWS char(1)
	, ZEITSEMESTER long varchar NOT NULL
	, PRUEFERNUMMER char(1) NOT NULL )
;

CREATE TABLE RAUM
	( RAUMNUMMER char(1) NOT NULL
	, GEBAEUDE char(1) NOT NULL
	, STANDORT long varchar NOT NULL
	, NAME long varchar NOT NULL )
;

CREATE TABLE SETZT_SICH_ZUSAMMEN_AUS
	( NAME long varchar NOT NULL
	, KUERZEL long varchar NOT NULL )
;

CREATE TABLE STUDIENGANG
	( SPO long varchar NOT NULL
	, ABSCHLUSS long varchar NOT NULL
	, ZEITSEMESTER long varchar NOT NULL
	, NAME long varchar NOT NULL
	, KUERZEL long varchar NOT NULL )
;

CREATE TABLE STUDIENSEMESTER
	( EINSTUFUNG long varchar NOT NULL )
;

CREATE TABLE TAETIGKEITEN
	( DWS char(1) NOT NULL
	, ID char(1) NOT NULL
	, NAME long varchar NOT NULL
	, ZEITSEMESTER long varchar NOT NULL
	, PRUEFERNUMMER char(1) NOT NULL
	, PRUEFERNUMMER_118 char(1) NOT NULL
	, KUERZEL long varchar NOT NULL )
;

CREATE TABLE VORLESUNGPLAN
	( NAME long varchar NOT NULL
	, ZEITSEMESTER long varchar NOT NULL
	, SWS char(1) NOT NULL
	, PRUEFERNUMMER char(1) NOT NULL
	, ZEITSEMESTER_370 long varchar NOT NULL )
;

CREATE TABLE VORLESUNGREAL
	( NAME long varchar NOT NULL
	, VORLESUNGSBLOCK char(1) NOT NULL )
;

ALTER TABLE ANSCHRIFT
	ADD CONSTRAINT PK PRIMARY KEY 
	( PRUEFERNUMMER );

ALTER TABLE BESUCHT
	ADD CONSTRAINT PK PRIMARY KEY 
	( NAME
	, EINSTUFUNG );

ALTER TABLE DOZENT
	ADD CONSTRAINT PK PRIMARY KEY 
	( PRUEFERNUMMER );

ALTER TABLE FAKULTAET
	ADD CONSTRAINT PK PRIMARY KEY 
	( KUERZEL );

ALTER TABLE HAT
	ADD CONSTRAINT PK PRIMARY KEY 
	( NAME
	, NAME_130 );

ALTER TABLE IST_EINE
	ADD CONSTRAINT PK PRIMARY KEY 
	( NAME
	, ID );

ALTER TABLE KANN_ANBIETEN
	ADD CONSTRAINT PK PRIMARY KEY 
	( PRUEFERNUMMER
	, NAME );

ALTER TABLE KANN_HABEN_HAT
	ADD CONSTRAINT PK PRIMARY KEY 
	( NAME
	, EINSTUFUNG );

ALTER TABLE LEHRBEAUFTRAGTE
	ADD CONSTRAINT PK PRIMARY KEY 
	( PRUEFERNUMMER );

ALTER TABLE LEHRT
	ADD CONSTRAINT PK PRIMARY KEY 
	( PRUEFERNUMMER
	, NAME );

ALTER TABLE PROFESSOR
	ADD CONSTRAINT PK PRIMARY KEY 
	( PRUEFERNUMMER
	, ZEITSEMESTER );

ALTER TABLE RAUM
	ADD CONSTRAINT PK PRIMARY KEY 
	( STANDORT
	, GEBAEUDE
	, RAUMNUMMER );

ALTER TABLE SETZT_SICH_ZUSAMMEN_AUS
	ADD CONSTRAINT PK PRIMARY KEY 
	( NAME
	, KUERZEL );

ALTER TABLE STUDIENGANG
	ADD CONSTRAINT PK PRIMARY KEY 
	( KUERZEL );

ALTER TABLE STUDIENSEMESTER
	ADD CONSTRAINT PK PRIMARY KEY 
	( EINSTUFUNG );

ALTER TABLE TAETIGKEITEN
	ADD CONSTRAINT PK PRIMARY KEY 
	( ID );

ALTER TABLE VORLESUNGPLAN
	ADD CONSTRAINT PK PRIMARY KEY 
	( NAME );

ALTER TABLE VORLESUNGREAL
	ADD CONSTRAINT PK PRIMARY KEY 
	( NAME );

ALTER TABLE ANSCHRIFT
	ADD CONSTRAINT ANSCHRIFT_DOZENT FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES DOZENT
	( PRUEFERNUMMER ); 

ALTER TABLE ANSCHRIFT
	ADD CONSTRAINT ANSCHRIFT_DOZENT_189 FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES DOZENT
	( PRUEFERNUMMER ); 

ALTER TABLE BESUCHT
	ADD CONSTRAINT STUDIENSEMESTER_VORLESUNGREAL_VORLESUNGREAL FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGREAL
	( NAME )
	ON DELETE CASCADE; 

ALTER TABLE BESUCHT
	ADD CONSTRAINT STUDIENSEMESTER_VORLESUNGREAL_STUDIENSEMESTER FOREIGN KEY
	( EINSTUFUNG )
	REFERENCES STUDIENSEMESTER
	( EINSTUFUNG )
	ON DELETE CASCADE; 

ALTER TABLE BESUCHT
	ADD CONSTRAINT STUDIENSEMESTER_VORLESUNGREAL_VORLESUNGREAL_158 FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGREAL
	( NAME ); 

ALTER TABLE BESUCHT
	ADD CONSTRAINT STUDIENSEMESTER_VORLESUNGREAL_STUDIENSEMESTER_159 FOREIGN KEY
	( EINSTUFUNG )
	REFERENCES STUDIENSEMESTER
	( EINSTUFUNG ); 

ALTER TABLE BESUCHT
	ADD CONSTRAINT BESUCHT_VORLESUNGREAL FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGREAL
	( NAME ); 

ALTER TABLE BESUCHT
	ADD CONSTRAINT BESUCHT_STUDIENSEMESTER FOREIGN KEY
	( EINSTUFUNG )
	REFERENCES STUDIENSEMESTER
	( EINSTUFUNG ); 

ALTER TABLE DOZENT
	ADD CONSTRAINT DOZENT_FAKULTAET FOREIGN KEY
	( KUERZEL )
	REFERENCES FAKULTAET
	( KUERZEL ); 

ALTER TABLE DOZENT
	ADD CONSTRAINT DOZENT_FAKULTAET_140 FOREIGN KEY
	( KUERZEL )
	REFERENCES FAKULTAET
	( KUERZEL ); 

ALTER TABLE DOZENT
	ADD CONSTRAINT DOZENT_FAKULTAET_188 FOREIGN KEY
	( KUERZEL )
	REFERENCES FAKULTAET
	( KUERZEL ); 

ALTER TABLE FAKULTAET
	ADD CONSTRAINT FAKULTAET_DOZENT FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES DOZENT
	( PRUEFERNUMMER ); 

ALTER TABLE FAKULTAET
	ADD CONSTRAINT FAKULTAET_DOZENT_141 FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES DOZENT
	( PRUEFERNUMMER ); 

ALTER TABLE FAKULTAET
	ADD CONSTRAINT FAKULTAET_DOZENT_192 FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES DOZENT
	( PRUEFERNUMMER ); 

ALTER TABLE HAT
	ADD CONSTRAINT HAT_VORLESUNGPLAN FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGPLAN
	( NAME )
	ON DELETE CASCADE; 

ALTER TABLE HAT
	ADD CONSTRAINT HAT_VORLESUNGREAL FOREIGN KEY
	( NAME_130 )
	REFERENCES VORLESUNGREAL
	( NAME )
	ON DELETE CASCADE; 

ALTER TABLE HAT
	ADD CONSTRAINT HAT_VORLESUNGPLAN_142 FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGPLAN
	( NAME ); 

ALTER TABLE HAT
	ADD CONSTRAINT HAT_VORLESUNGREAL_143 FOREIGN KEY
	( NAME_130 )
	REFERENCES VORLESUNGREAL
	( NAME ); 

ALTER TABLE HAT
	ADD CONSTRAINT HAT_VORLESUNGPLAN_193 FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGPLAN
	( NAME ); 

ALTER TABLE HAT
	ADD CONSTRAINT HAT_VORLESUNGREAL_194 FOREIGN KEY
	( NAME_130 )
	REFERENCES VORLESUNGREAL
	( NAME ); 

ALTER TABLE IST_EINE
	ADD CONSTRAINT IST_EINE_VORLESUNGREAL FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGREAL
	( NAME )
	ON DELETE CASCADE; 

ALTER TABLE IST_EINE
	ADD CONSTRAINT IST_EINE_TAETIGKEITEN FOREIGN KEY
	( ID )
	REFERENCES TAETIGKEITEN
	( ID )
	ON DELETE CASCADE; 

ALTER TABLE IST_EINE
	ADD CONSTRAINT IST_EINE_VORLESUNGREAL_144 FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGREAL
	( NAME ); 

ALTER TABLE IST_EINE
	ADD CONSTRAINT IST_EINE_TAETIGKEITEN_145 FOREIGN KEY
	( ID )
	REFERENCES TAETIGKEITEN
	( ID ); 

ALTER TABLE IST_EINE
	ADD CONSTRAINT IST_EINE_VORLESUNGREAL_195 FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGREAL
	( NAME ); 

ALTER TABLE IST_EINE
	ADD CONSTRAINT IST_EINE_TAETIGKEITEN_196 FOREIGN KEY
	( ID )
	REFERENCES TAETIGKEITEN
	( ID ); 

ALTER TABLE KANN_ANBIETEN
	ADD CONSTRAINT KANN_ANBIETEN_DOZENT FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES DOZENT
	( PRUEFERNUMMER )
	ON DELETE CASCADE; 

ALTER TABLE KANN_ANBIETEN
	ADD CONSTRAINT KANN_ANBIETEN_VORLESUNGPLAN FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGPLAN
	( NAME )
	ON DELETE CASCADE; 

ALTER TABLE KANN_ANBIETEN
	ADD CONSTRAINT KANN_ANBIETEN_DOZENT_146 FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES DOZENT
	( PRUEFERNUMMER ); 

ALTER TABLE KANN_ANBIETEN
	ADD CONSTRAINT KANN_ANBIETEN_VORLESUNGPLAN_147 FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGPLAN
	( NAME ); 

ALTER TABLE KANN_ANBIETEN
	ADD CONSTRAINT KANN_ANBIETEN_DOZENT_197 FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES DOZENT
	( PRUEFERNUMMER ); 

ALTER TABLE KANN_ANBIETEN
	ADD CONSTRAINT KANN_ANBIETEN_VORLESUNGPLAN_198 FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGPLAN
	( NAME ); 

ALTER TABLE KANN_HABEN_HAT
	ADD CONSTRAINT KANN_HABEN_HAT_VORLESUNGPLAN FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGPLAN
	( NAME )
	ON DELETE CASCADE; 

ALTER TABLE KANN_HABEN_HAT
	ADD CONSTRAINT KANN_HABEN_HAT_STUDIENSEMESTER FOREIGN KEY
	( EINSTUFUNG )
	REFERENCES STUDIENSEMESTER
	( EINSTUFUNG )
	ON DELETE CASCADE; 

ALTER TABLE KANN_HABEN_HAT
	ADD CONSTRAINT KANN_HABEN_HAT_VORLESUNGPLAN_148 FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGPLAN
	( NAME ); 

ALTER TABLE KANN_HABEN_HAT
	ADD CONSTRAINT KANN_HABEN_HAT_STUDIENSEMESTER_149 FOREIGN KEY
	( EINSTUFUNG )
	REFERENCES STUDIENSEMESTER
	( EINSTUFUNG ); 

ALTER TABLE KANN_HABEN_HAT
	ADD CONSTRAINT KANN_HABEN_HAT_VORLESUNGPLAN_199 FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGPLAN
	( NAME ); 

ALTER TABLE KANN_HABEN_HAT
	ADD CONSTRAINT KANN_HABEN_HAT_STUDIENSEMESTER_200 FOREIGN KEY
	( EINSTUFUNG )
	REFERENCES STUDIENSEMESTER
	( EINSTUFUNG ); 

ALTER TABLE LEHRBEAUFTRAGTE
	ADD CONSTRAINT LEHRBEAUFTRAGTE_DOZENT FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES DOZENT
	( PRUEFERNUMMER )
	ON DELETE CASCADE; 

ALTER TABLE LEHRBEAUFTRAGTE
	ADD CONSTRAINT LEHRBEAUFTRAGTE_DOZENT_150 FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES DOZENT
	( PRUEFERNUMMER )
	ON DELETE CASCADE; 

ALTER TABLE LEHRBEAUFTRAGTE
	ADD CONSTRAINT LEHRBEAUFTRAGTE_DOZENT_201 FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES DOZENT
	( PRUEFERNUMMER )
	ON DELETE CASCADE; 

ALTER TABLE LEHRT
	ADD CONSTRAINT LEHRT_DOZENT FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES DOZENT
	( PRUEFERNUMMER )
	ON DELETE CASCADE; 

ALTER TABLE LEHRT
	ADD CONSTRAINT LEHRT_VORLESUNGREAL FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGREAL
	( NAME )
	ON DELETE CASCADE; 

ALTER TABLE LEHRT
	ADD CONSTRAINT LEHRT_DOZENT_151 FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES DOZENT
	( PRUEFERNUMMER ); 

ALTER TABLE LEHRT
	ADD CONSTRAINT LEHRT_VORLESUNGREAL_152 FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGREAL
	( NAME ); 

ALTER TABLE LEHRT
	ADD CONSTRAINT LEHRT_DOZENT_202 FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES DOZENT
	( PRUEFERNUMMER ); 

ALTER TABLE LEHRT
	ADD CONSTRAINT LEHRT_VORLESUNGREAL_203 FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGREAL
	( NAME ); 

ALTER TABLE PROFESSOR
	ADD CONSTRAINT PROFESSOR_DOZENT FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES DOZENT
	( PRUEFERNUMMER )
	ON DELETE CASCADE; 

ALTER TABLE PROFESSOR
	ADD CONSTRAINT PROFESSOR_DOZENT_153 FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES DOZENT
	( PRUEFERNUMMER )
	ON DELETE CASCADE; 

ALTER TABLE PROFESSOR
	ADD CONSTRAINT PROFESSOR_DOZENT_204 FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES DOZENT
	( PRUEFERNUMMER )
	ON DELETE CASCADE; 

ALTER TABLE RAUM
	ADD CONSTRAINT RAUM_VORLESUNGREAL FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGREAL
	( NAME ); 

ALTER TABLE RAUM
	ADD CONSTRAINT RAUM_VORLESUNGREAL_154 FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGREAL
	( NAME ); 

ALTER TABLE RAUM
	ADD CONSTRAINT RAUM_VORLESUNGREAL_205 FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGREAL
	( NAME ); 

ALTER TABLE SETZT_SICH_ZUSAMMEN_AUS
	ADD CONSTRAINT SETZT_SICH_ZUSAMMEN_AUS_VORLESUNGPLAN FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGPLAN
	( NAME )
	ON DELETE CASCADE; 

ALTER TABLE SETZT_SICH_ZUSAMMEN_AUS
	ADD CONSTRAINT SETZT_SICH_ZUSAMMEN_AUS_STUDIENGANG FOREIGN KEY
	( KUERZEL )
	REFERENCES STUDIENGANG
	( KUERZEL )
	ON DELETE CASCADE; 

ALTER TABLE SETZT_SICH_ZUSAMMEN_AUS
	ADD CONSTRAINT SETZT_SICH_ZUSAMMEN_AUS_VORLESUNGPLAN_155 FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGPLAN
	( NAME ); 

ALTER TABLE SETZT_SICH_ZUSAMMEN_AUS
	ADD CONSTRAINT SETZT_SICH_ZUSAMMEN_AUS_STUDIENGANG_156 FOREIGN KEY
	( KUERZEL )
	REFERENCES STUDIENGANG
	( KUERZEL ); 

ALTER TABLE SETZT_SICH_ZUSAMMEN_AUS
	ADD CONSTRAINT SETZT_SICH_ZUSAMMEN_AUS_VORLESUNGPLAN_206 FOREIGN KEY
	( NAME )
	REFERENCES VORLESUNGPLAN
	( NAME ); 

ALTER TABLE SETZT_SICH_ZUSAMMEN_AUS
	ADD CONSTRAINT SETZT_SICH_ZUSAMMEN_AUS_STUDIENGANG_207 FOREIGN KEY
	( KUERZEL )
	REFERENCES STUDIENGANG
	( KUERZEL ); 

ALTER TABLE STUDIENGANG
	ADD CONSTRAINT STUDIENGANG_FAKULTAET FOREIGN KEY
	( KUERZEL )
	REFERENCES FAKULTAET
	( KUERZEL ); 

ALTER TABLE STUDIENGANG
	ADD CONSTRAINT STUDIENGANG_FAKULTAET_157 FOREIGN KEY
	( KUERZEL )
	REFERENCES FAKULTAET
	( KUERZEL ); 

ALTER TABLE STUDIENGANG
	ADD CONSTRAINT STUDIENGANG_FAKULTAET_208 FOREIGN KEY
	( KUERZEL )
	REFERENCES FAKULTAET
	( KUERZEL ); 

ALTER TABLE TAETIGKEITEN
	ADD CONSTRAINT TAETIGKEITEN_DOZENT FOREIGN KEY
	( PRUEFERNUMMER_118 )
	REFERENCES DOZENT
	( PRUEFERNUMMER ); 

ALTER TABLE TAETIGKEITEN
	ADD CONSTRAINT TAETIGKEITEN_FAKULTAET FOREIGN KEY
	( KUERZEL )
	REFERENCES FAKULTAET
	( KUERZEL ); 

ALTER TABLE TAETIGKEITEN
	ADD CONSTRAINT TAETIGKEITEN_DOZENT_160 FOREIGN KEY
	( PRUEFERNUMMER_118 )
	REFERENCES DOZENT
	( PRUEFERNUMMER ); 

ALTER TABLE TAETIGKEITEN
	ADD CONSTRAINT TAETIGKEITEN_FAKULTAET_161 FOREIGN KEY
	( KUERZEL )
	REFERENCES FAKULTAET
	( KUERZEL ); 

ALTER TABLE TAETIGKEITEN
	ADD CONSTRAINT TAETIGKEITEN_DOZENT_209 FOREIGN KEY
	( PRUEFERNUMMER_118 )
	REFERENCES DOZENT
	( PRUEFERNUMMER ); 

ALTER TABLE TAETIGKEITEN
	ADD CONSTRAINT TAETIGKEITEN_FAKULTAET_210 FOREIGN KEY
	( KUERZEL )
	REFERENCES FAKULTAET
	( KUERZEL ); 

ALTER TABLE VORLESUNGPLAN
	ADD CONSTRAINT VORLESUNGPLAN_PROFESSOR FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES PROFESSOR
	( PRUEFERNUMMER ); 

ALTER TABLE VORLESUNGPLAN
	ADD CONSTRAINT VORLESUNGPLAN_PROFESSOR_162 FOREIGN KEY
	( PRUEFERNUMMER )
	REFERENCES PROFESSOR
	( PRUEFERNUMMER ); 

ALTER TABLE VORLESUNGPLAN
	ADD CONSTRAINT VORLESUNGPLAN_PROFESSOR_211 FOREIGN KEY
	( PRUEFERNUMMER
	, ZEITSEMESTER_370 )
	REFERENCES PROFESSOR
	( PRUEFERNUMMER
	, ZEITSEMESTER ); 

