ID, Zeitsemester, SWS, Name, Pruefernummer, Studiengang


INSERT INTO VORLESUNG_PLAN
(ID, ZEITSEMESTER, SEMESTERWOCHENSTUNDEN, NAME, PRUEFERNUMMER, STUDIENGANG_ID)
VALUES
(SELECT spo.MODULNR, spo.SEMESTER, (spo.CREDITS*8) ,spo.TEILGEBIET, sp.Pruefernummer, studgang.ID
FROM TD_SPO as spo
INNER JOIN STUDIENGANG as studgang
ON spo.STUDIENGANG = studgang.NAME
INNER JOIN STUNDENPLAN as sp
ON spo.MODULNAME = sp.Fach
GROUP BY spo.MODULNR, spo.SEMESTER, spo.TEILGEBIET, spo.STUDIENGANG)