--PLZ 5-stellig
ALTER TABLE ANSCHRIFT
  ADD CONSTRAINT PLZ_Length
  CHECK (length(rtrim(plz)) = 5);

-- DWS bei TAETIGKEIT Update
CREATE TRIGGER DWS_UPDATE_ADD
  AFTER INSERT ON TAETIGKEIT
  REFERENCING NEW AS n
  FOR EACH ROW MODE DB2SQL
    UPDATE PROFESSOR
    SET DWS = DWS + n.DWS
    WHERE n.PRUEFERNUMMER = PRUEFERNUMMER
    AND n.ZEITSEMESTER = ZEITSEMESTER
;

CREATE TRIGGER DWS_UPDATE_SUB
  AFTER DELETE ON TAETIGKEIT
  REFERENCING OLD AS o
  FOR EACH ROW MODE DB2SQL
      UPDATE PROFESSOR
      SET DWS = DWS - o.DWS
      WHERE o.PRUEFERNUMMER = PRUEFERNUMMER
      AND o.ZEITSEMESTER = ZEITSEMESTER
;

CREATE Trigger DWS_Update
  AFTER UPDATE ON TAETIGKEIT
  REFERENCING OLD AS o
  REFERENCING NEW AS n
  FOR EACH ROW MODE DB2SQL
    UPDATE PROFESSOR
    SET DWS = DWS - o.DWS + n.DWS
    WHERE o.PRUEFERNUMMER = PRUEFERNUMMER
    AND o.ZEITSEMESTER = n.ZEITSEMESTER
;
